apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    weave.works/capi: bootstrap
  name: test1
  namespace: default
spec:
  capiClusterRef:
    name: test1

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: cilium
    weave.works/capi: bootstrap
  name: test1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.25.0.0/16
    services:
      cidrBlocks:
      - 172.26.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: test1-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: MicrovmCluster
    name: test1

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: MicrovmCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test1
  namespace: default
spec:
  bundleLookupBaseRegistry: projects.registry.vmware.com/cluster_api_provider_bringyourownhost
  controlPlaneEndpoint:
    host: 192.168.10.25
    port: 6443
  placement:
    staticPool:
      hosts:
      - controlplaneAllowed: true
        endpoint: 145.40.97.33:9090
  sshPublicKeys:
  - authorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCWIkWQdEF0Wlvak13wdA/1eWtt6Ni+2YAO12O3clUo4FA7NOhBU6d56kZDLszipGEQycDtQOZP3mxK9svnQrqlwOwAPCuvLmy88BLRKDy0KwOKOTNfeFMBKoH8bdfLey6eME9LJKOOKHzZwsabH5M4R+Mr1rkAZGKOyNewzyjeFpBGM+z1am9obVWhCvoCVLG7/3aJM4cC79p/zSmjr30SxkymWFWcbgAy+RSQLMWRA9STuqf5Rt2Mn6Z6ZqzlgXb/K6XqTAfC+VpiNnfY1xrZy9G+ATu9cTiz1nkpbXzrFd3Skz8Rz3pacEDO4sENc4erMDUFmlX8jwn99kG8TGZ+yYUvLIBqsiZaEtKR3/GVkSchVNliJUBxKJgPalU/MEwDWUFPqlFjghtLmUzdAGNnZ0NU+rAx3gDjqwagXlZGPmd+SOe0JGJ1hMTLtFWKhBxKWk/r6Y1bS+/Kum5uc1QVkZMIQFlzcXsPVZf0k4TovzwByG4qBqpxGrvSHhMCDkXd4fcDusyMvxSqr+RKEuoWD8SDExNJHa/cqkW9kQCESVPO0rXz5Jd6mFjPF70vTGfghRvjFfEl8UOqggWwpCeT4NZn7r5/wER/15wY0y9oAz7xDRlMbqEWVRnuncBKSTu3bUFW2xUUQSNuMOavyxBlihoz+mapQY1Y0de8lEurcQ==
      richard@kraken
    user: root

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test1-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration: {}
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: microvm://{{ ds.meta_data.vm_host }}/{{ ds.meta_data.instance_id
            }}
    joinConfiguration:
      nodeRegistration:
        ignorePreflightErrors:
        - DirAvailable--etc-kubernetes-manifests
        kubeletExtraArgs:
          provider-id: microvm://{{ ds.meta_data.vm_host }}/{{ ds.meta_data.instance_id
            }}
    preKubeadmCommands:
    - mkdir -p /etc/kubernetes/manifests && ctr images pull ghcr.io/kube-vip/kube-vip:v0.5.0
      && ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:v0.5.0 vip /kube-vip manifest
      pod --arp --interface $(ip -4 -j route list default | jq -r .[0].dev) --address
      192.168.10.25 --controlplane --leaderElection > /etc/kubernetes/manifests/kube-vip.yaml
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: MicrovmMachineTemplate
      name: test1-control-plane
  replicas: 1
  version: v1.23.5

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: MicrovmMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test1-control-plane
  namespace: default
spec:
  template:
    spec:
      kernel:
        filename: boot/vmlinux
        image: ghcr.io/weaveworks-liquidmetal/flintlock-kernel:5.10.77
      kernelCmdline: {}
      memoryMb: 2048
      networkInterfaces:
      - guestDeviceName: eth1
        type: macvtap
      rootVolume:
        id: root
        image: ghcr.io/weaveworks-liquidmetal/capmvm-kubernetes:1.23.5
      vcpu: 2

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test1-md-0
  namespace: default
spec:
  clusterName: test1
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: test1-md-0
      clusterName: test1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ByoMachineTemplate
        name: test1-md-0
      version: v1.23.5

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ByoMachineTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      installerRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: K8sInstallerConfigTemplate
        name: test1-md-0
        namespace: default

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test1-md-0
  namespace: default
spec:
  template:
    spec: {}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: K8sInstallerConfigTemplate
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: test1-md-0
  namespace: default
spec:
  template:
    spec:
      bundleRepo: projects.registry.vmware.com/cluster_api_provider_bringyourownhost
      bundleType: k8s
